version: "3.9"

services:
  db:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    volumes:
      - 'postgres_data:/data'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"

volumes:
  postgres_data:
    external: true
