version: "3.9"

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - 'postgres_data:/data'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"
  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb?schema=public"
    depends_on:
      - db
    command: "npm run dev"
    volumes:
      - .:/usr/src/app
  studio:
    build: .
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb?schema=public"
    depends_on:
      - db
    command: "npx prisma studio"
    volumes:
      - .:/usr/src/app


volumes:
  postgres_data:
    external: true
